In [ ]:
#Drive mount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os  #define path of file and directory
from skimage.io import imread # used for reading image
from sklearn.model_selection import train_test_split
from skimage.transform import resize

In [ ]:
os.listdir('/content/drive/MyDrive/Data')

['Cat', 'Dog']

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))

68

In [ ]:
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')  #to join data and Cat folder we can also give cat path without using join
for img in os.listdir(catpath):
  print(img)

cat.103.jpg
cat.107.jpg
cat.105.jpg
cat.110.jpg
cat.102.jpg
cat.104.jpg
cat.111.jpg
cat.108.jpg
cat.101.jpg
cat.109.jpg
cat.100.jpg
cat.106.jpg
cat.116.jpg
cat.118.jpg
cat.117.jpg
cat.113.jpg
cat.119.jpg
cat.115.jpg
cat.112.jpg
cat.114.jpg
cat.57.jpg
cat.55.jpg
cat.35.jpg
cat.37.jpg
cat.51.jpg
cat.41.jpg
cat.54.jpg
cat.45.jpg
cat.62.jpg
cat.38.jpg
cat.52.jpg
cat.56.jpg
cat.43.jpg
cat.58.jpg
cat.48.jpg
cat.61.jpg
cat.39.jpg
cat.53.jpg
cat.46.jpg
cat.49.jpg
cat.44.jpg
cat.59.jpg
cat.42.jpg
cat.50.jpg
cat.36.jpg
cat.60.jpg
cat.40.jpg
cat.47.jpg
cat.63.jpg
cat.95.jpg
cat.99.jpg
cat.92.jpg
cat.97.jpg
cat.69.jpg
cat.81.jpg
cat.93.jpg
cat.76.jpg
cat.66.jpg
cat.73.jpg
cat.77.jpg
cat.65.jpg
cat.89.jpg
cat.82.jpg
cat.96.jpg
cat.71.jpg
cat.80.jpg
cat.70.jpg
cat.83.jpg
cat.88.jpg
cat.91.jpg
cat.67.jpg
cat.87.jpg
cat.90.jpg
cat.79.jpg
cat.72.jpg
cat.74.jpg
cat.64.jpg
cat.86.jpg
cat.98.jpg
cat.75.jpg
cat.68.jpg
cat.94.jpg
cat.78.jpg
cat.85.jpg
cat.84.jpg


In [ ]:
dogpath=os.path.join('/content/drive/MyDrive/Data','Dog')  #to join data and Cat folder we can also give cat path without using join
for img in os.listdir(dogpath):
  print(img)

dog.1.jpg
dog.11.jpg
dog.10.jpg
dog.12.jpg
dog.15.jpg
dog.13.jpg
dog.14.jpg
dog.21.jpg
dog.22.jpg
dog.18.jpg
dog.23.jpg
dog.19.jpg
dog.16.jpg
dog.24.jpg
dog.2.jpg
dog.17.jpg
dog.20.jpg
dog.29.jpg
dog.31.jpg
dog.33.jpg
dog.28.jpg
dog.26.jpg
dog.25.jpg
dog.3.jpg
dog.30.jpg
dog.27.jpg
dog.32.jpg
dog.51.jpg
dog.53.jpg
dog.60.jpg
dog.38.jpg
dog.35.jpg
dog.48.jpg
dog.56.jpg
dog.46.jpg
dog.40.jpg
dog.59.jpg
dog.44.jpg
dog.41.jpg
dog.42.jpg
dog.4.jpg
dog.36.jpg
dog.47.jpg
dog.54.jpg
dog.5.jpg
dog.58.jpg
dog.39.jpg
dog.57.jpg
dog.52.jpg
dog.37.jpg
dog.50.jpg
dog.34.jpg
dog.49.jpg
dog.6.jpg
dog.43.jpg
dog.45.jpg
dog.55.jpg
dog.7.jpg
dog.62.jpg
dog.68.jpg
dog.61.jpg
dog.67.jpg
dog.8.jpg
dog.63.jpg
dog.64.jpg
dog.9.jpg
dog.65.jpg
dog.66.jpg


In [ ]:
flat_data_arr=[] #used to collect input data
target_arr=[]   #used for collect output data
categories=['Cat','Dog']
datadir='/content/drive/MyDrive/Data'

In [ ]:
for i in categories:
  print("Loading categories......")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):   #for j in os.listdir(path):
    img_arr=imread(os.path.join(path,img))  #imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))  #RGB
    flat_data_arr.append(img_resize.flatten())
    target_arr.append(categories.index(i))  #0 1
  print("Loaded completely",i)

Loading categories......
Loaded completely Cat
Loading categories......
Loaded completely Dog


In [ ]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)

df=pd.DataFrame(flat_data)
df

0         1         2         3         4         5         6      \
0    0.601961  0.617647  0.613726  0.604402  0.620088  0.616167  0.597635   
1    0.186657  0.186640  0.221778  0.191698  0.191680  0.226823  0.186147   
2    0.408366  0.376993  0.333856  0.431765  0.400393  0.357255  0.500325   
3    0.654589  0.092548  0.203156  0.643521  0.093398  0.199501  0.633144   
4    0.567769  0.512867  0.461886  0.573767  0.518865  0.467885  0.545760   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.383067  0.386150  0.303591  0.394106  0.397188  0.314629  0.406612   
149  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922   
150  0.815650  0.849131  0.845227  0.933889  0.955618  0.969236  0.891768   
151  0.868126  0.824222  0.832039  0.803477  0.760941  0.767098  0.871503   
152  0.379472  0.528492  0.194307  0.377842  0.527678  0.186123  0.376462   

        7         8         9      ...     67490     67491     67492  \
0    0.613321  0.609399  0.596407  ...  0.680711  0.632742  0.635138   
1    0.186129  0.221276  0.182267  ...  0.221204  0.322640  0.232582   
2    0.468953  0.425815  0.478301  ...  0.124019  0.832719  0.695464   
3    0.093794  0.195976  0.627333  ...  0.196421  0.644119  0.166650   
4    0.490858  0.439877  0.557858  ...  0.521950  0.728231  0.660557   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.409694  0.327135  0.387642  ...  0.297777  0.267342  0.340032   
149  0.003922  0.003922  0.003922  ...  0.003922  0.003922  0.003922   
150  0.905157  0.937564  0.477821  ...  0.094129  0.313858  0.429106   
151  0.835795  0.839717  0.891882  ...  0.405198  0.491852  0.605904   
152  0.529329  0.174595  0.376284  ...  0.074985  0.350342  0.554265   

        67493     67494     67495     67496     67497     67498     67499  
0    0.645287  0.631576  0.633479  0.642293  0.690567  0.689876  0.689292  
1    0.220778  0.307843  0.229316  0.221181  0.307185  0.221946  0.231622  
2    0.138601  0.849192  0.708016  0.158996  0.850358  0.709182  0.165814  
3    0.215340  0.686256  0.145864  0.234624  0.698753  0.139866  0.235372  
4    0.600644  0.698120  0.629841  0.567903  0.732229  0.653866  0.600209  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.137523  0.363487  0.444638  0.189242  0.362599  0.440701  0.184744  
149  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  
150  0.209400  0.405920  0.508851  0.307331  0.362543  0.453008  0.271112  
151  0.386950  0.477503  0.591229  0.371621  0.467608  0.577477  0.350157  
152  0.122808  0.348114  0.553508  0.121114  0.341176  0.559507  0.117435  

[153 rows x 67500 columns]

In [ ]:
df.shape

(153, 67500)

In [ ]:
df['Target']=target_data
df.shape

(153, 67501)

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)


In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
con=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
con

array([[12,  8],
       [ 8,  3]])

In [ ]:
score

0.4838709677419355

In [ ]:
path1='/content/drive/MyDrive/cat dog/Cat03.jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])

In [ ]:
path2='/content/drive/MyDrive/cat dog/bernese-mountain-dog.jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])

In [ ]:
path3='/content/drive/MyDrive/cat dog/1655430860853.jpeg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])

In [ ]:
path4='/content/drive/MyDrive/cat dog/images.jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])

In [ ]:
path5='/content/drive/MyDrive/cat dog/kitten.jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])

In [ ]:
path6='/content/drive/MyDrive/cat dog/images (1).jpg'
img=imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([1])